### ISSUE TITLE
Little Confused

### ISSUE THREAD

**Issue by iGetUploaded** [Tomato6966/voice-controlled-discord-bot#2]
So I followed the steps below *self-hosting* and all that works. But when I do v!control and then bot comes in and tells you to say ***bot play shape of you*** I do and it records my voice in console but throws out an error I'm not sure how to solve 

Here is the error: 
![image](https://user-images.githubusercontent.com/54633753/182011781-43e9e9ba-c2f0-453b-9bc3-2c35c8a2ddc4.png)

**Comment by Tomato6966** [comment]
is there a .pcm file inside the /temp folder
?

**Comment by iGetUploaded** [comment]
Hi Sorry for late response but yes there is 
![image](https://user-images.githubusercontent.com/54633753/182040521-d90f97f2-10f3-4742-876f-34578398b84c.png)

**Comment by Tomato6966** [comment]
oh ur on windows, it's not tested on windows, prolly not working try on linux

**Comment by iGetUploaded** [comment]
Sorry I didn't respond my PC broke the day I posted the picture. Thanks for letting me know its not tested on windows though
