### ISSUE TITLE
Some Errors Are Comming Up Kindly Solve This

### ISSUE THREAD

**Issue by TamilanMessi** [Tomato6966/voice-controlled-discord-bot#3]
![image](https://user-images.githubusercontent.com/94314207/183668398-6d32d97f-38f1-4627-9ae1-0dfdeaacd98d.png)
Check These Errors The Bot Is Not Replying

**Comment by ghost** [comment]
I had this too, thought it was weird so I just deleted the line where the error was coming from

**Comment by Screenmax1234** [comment]
no no guys you just need to do npm install ytdl-core@latest
