### ISSUE TITLE
Issue with running this as specified

### ISSUE THREAD

**Issue by JackJBlundell** [Tomato6966/voice-controlled-discord-bot#6]
Hey there!

Firstly @Tomato6966 I take my hat off to you - I have looked for nearly a month now for suitably made voice projects that I could learn from, and yours is 100000 miles better than any other - I am sincerely indebted to you!

Can you help me out - I am having an issue following your instructions, and when running the code I am faced with this error:

`
[antiCrash] :: Unhandled Rejection/Catch
Error: Could not locate the bindings file. Tried:
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/20.11.1/darwin/arm64/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v115-darwin-arm64/crc.node
    at bindings (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/src/lib.js:1:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/ogg/OggLogicalBitstream.js:50:19)
    at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/opus/OggLogicalBitstream.js:13:9) {
  tries: [
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/20.11.1/darwin/arm64/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v115-darwin-arm64/crc.node'
  ]
} Promise {
  <rejected> Error: Could not locate the bindings file. Tried:
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/20.11.1/darwin/arm64/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v115-darwin-arm64/crc.node
      at bindings (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/bindings/bindings.js:126:9)
      at Object.<anonymous> (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/src/lib.js:1:32)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/ogg/OggLogicalBitstream.js:50:19)
      at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/opus/OggLogicalBitstream.js:13:9) {
    tries: [
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/20.11.1/darwin/arm64/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v115-darwin-arm64/crc.node'
    ]
  }
}
`

I think I may be using a different version of Node from you, can you help me by letting me know which version you used for this proejct to compile it? Or if you have any ideas of how to fix I would really appreciate it.

Thanks!

**Comment by JackJBlundell** [comment]
Closed because i **properly read your ReadMe** 😂

Sorry & thanks again for everything you did here, tremendous work

**Comment by JackJBlundell** [comment]
Re-opening as I am still facing the same error when using 16.10.0 of Node.js.

Specifically facing this error:



`
 [antiCrash] :: Unhandled Rejection/Catch
Error: Could not locate the bindings file. Tried:
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/16.10.0/darwin/arm64/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node
 → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v93-darwin-arm64/crc.node
    at bindings (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/src/lib.js:1:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/ogg/OggLogicalBitstream.js:50:19)
    at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/opus/OggLogicalBitstream.js:13:9) {
  tries: [
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/16.10.0/darwin/arm64/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node',
    '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v93-darwin-arm64/crc.node'
  ]
} Promise {
  <rejected> Error: Could not locate the bindings file. Tried:
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/16.10.0/darwin/arm64/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node
   → /Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v93-darwin-arm64/crc.node
      at bindings (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/bindings/bindings.js:126:9)
      at Object.<anonymous> (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/src/lib.js:1:32)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/ogg/OggLogicalBitstream.js:50:19)
      at new OggLogicalBitstream (/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/prism-media/dist/opus/OggLogicalBitstream.js:13:9) {
    tries: [
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Debug/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/out/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/Release/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/build/default/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/compiled/16.10.0/darwin/arm64/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/release/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/debug/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/addon-build/default/install-root/crc.node',
      '/Users/jackblundell/Desktop/voice-controlled-discord-bot/node_modules/node-crc/lib/binding/node-v93-darwin-arm64/crc.node'
    ]
  }
}
`

Any ideas @Tomato6966 ?

**Comment by Tomato6966** [comment]
something went wrong during npm install

make sure you have properly installed python 2.7 and added it to your paths of "python" and installed all build-tools.
Then delete node_modules and re-install them

**Comment by Tomato6966** [comment]
Also thanks for the compliment

**Comment by JackJBlundell** [comment]
Hey thank you @Tomato6966  - You were right and it was to do with the version of Python being used as well as some other local config (Need to use Node 16.11).

I would recommend perhaps updating the parseAudioData method you have - I couldn't get the parsing to work or the app until i changed it to this way of saving the PCM file (Ignore my duration change this is for my specific project requirements):

```
async function parseAudioData(client, VoiceConnection, user, channel) {
  // create the filename of it
  const filename = `${process.cwd()}/temp/${transformUsername(
    user.username
  )}_${Date.now()}.pcm`;
  // then make a listenable audio stream, with the maximum highWaterMark (longest duration(s))
  const audioStream = VoiceConnection.receiver.subscribe(user.id, {
    end: {
      behavior: EndBehaviorType.AfterSilence,
      duration: 4000,
    },
    highWaterMark: 1 << 16,
  });
  const writeStream = fs.createWriteStream(filename);

  const opusDecoder = new prism.opus.Decoder({
    frameSize: 960,
    channels: 2,
    rate: 48000,
  });

  audioStream.pipe(opusDecoder).pipe(writeStream);

  console.log(`👂 Started recording ${filename}`);
  const msg = await channel
    .send({
      content: translate(
        client,
        channel.guild.id,
        "NOWLISTENING",
        user.tag,
        msUnix(Date.now() + 5_000)
      ),
    })
    .catch(() => null);

  writeStream.on("close", async () => {
    console.log("OUT finished");

    return await handlePCMFile(
      client,
      VoiceConnection,
      user,
      channel,
      msg,
      filename
    );
  });
}
```

And no need for thanks - Sincerely I was so glad to of found this and now to be able to go into my Discord and utilise this and expand on it for my own needs, is so great, thank you!

P.s. Worth noting I had to downgrade prism to the non-beta version

**Comment by Tomato6966** [comment]
Thanks for your input. I am not maintaining any old projects due to personal reasons anymore. but still provide them for users who want to take a look
